/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDiscountsRouteImport } from './routes/_app.discounts'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppPosIndexRouteImport } from './routes/_app.pos.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app.notifications.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppDiscountsIndexRouteImport } from './routes/_app.discounts.index'
import { Route as AppBillingIndexRouteImport } from './routes/_app.billing.index'
import { Route as AppSettingsTallyRouteImport } from './routes/_app.settings.tally'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsPaymentGatewayRouteImport } from './routes/_app.settings.payment-gateway'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppSettingsAttendanceRouteImport } from './routes/_app.settings.attendance'
import { Route as AppReportsSalesRouteImport } from './routes/_app.reports.sales'
import { Route as AppReportsInventoryRouteImport } from './routes/_app.reports.inventory'
import { Route as AppReportsFinancialRouteImport } from './routes/_app.reports.financial'
import { Route as AppReportsExportRouteImport } from './routes/_app.reports.export'
import { Route as AppReportsEmployeeRouteImport } from './routes/_app.reports.employee'
import { Route as AppReportsDiscountRouteImport } from './routes/_app.reports.discount'
import { Route as AppReportsAttendanceRouteImport } from './routes/_app.reports.attendance'
import { Route as AppPosTransactionsRouteImport } from './routes/_app.pos.transactions'
import { Route as AppPosSettingsRouteImport } from './routes/_app.pos.settings'
import { Route as AppPosSearchRouteImport } from './routes/_app.pos.search'
import { Route as AppPosQrRouteImport } from './routes/_app.pos.qr'
import { Route as AppPosBarcodeRouteImport } from './routes/_app.pos.barcode'
import { Route as AppNotificationsSystemRouteImport } from './routes/_app.notifications.system'
import { Route as AppNotificationsPaymentRouteImport } from './routes/_app.notifications.payment'
import { Route as AppNotificationsLowStockRouteImport } from './routes/_app.notifications.low-stock'
import { Route as AppNotificationsAttendanceRouteImport } from './routes/_app.notifications.attendance'
import { Route as AppInventoryStockOutwardRouteImport } from './routes/_app.inventory.stock-outward'
import { Route as AppInventoryStockInwardRouteImport } from './routes/_app.inventory.stock-inward'
import { Route as AppInventoryStockAdjustmentRouteImport } from './routes/_app.inventory.stock-adjustment'
import { Route as AppInventoryReportsRouteImport } from './routes/_app.inventory.reports'
import { Route as AppInventoryProductsRouteImport } from './routes/_app.inventory.products'
import { Route as AppInventoryHistoryRouteImport } from './routes/_app.inventory.history'
import { Route as AppInventoryCategoriesRouteImport } from './routes/_app.inventory.categories'
import { Route as AppInventoryAlertsRouteImport } from './routes/_app.inventory.alerts'
import { Route as AppEmployeesReportsRouteImport } from './routes/_app.employees.reports'
import { Route as AppEmployeesProfileRouteImport } from './routes/_app.employees.profile'
import { Route as AppEmployeesLoginMonitoringRouteImport } from './routes/_app.employees.login-monitoring'
import { Route as AppEmployeesLocationRouteImport } from './routes/_app.employees.location'
import { Route as AppEmployeesAddRouteImport } from './routes/_app.employees.add'
import { Route as AppEmployeesActivityRouteImport } from './routes/_app.employees.activity'
import { Route as AppDiscountsUsageReportsRouteImport } from './routes/_app.discounts.usage-reports'
import { Route as AppDiscountsSeasonalRouteImport } from './routes/_app.discounts.seasonal'
import { Route as AppDiscountsProductsRouteImport } from './routes/_app.discounts.products'
import { Route as AppDiscountsPercentageRouteImport } from './routes/_app.discounts.percentage'
import { Route as AppDiscountsFlatRouteImport } from './routes/_app.discounts.flat'
import { Route as AppDiscountsCategoriesRouteImport } from './routes/_app.discounts.categories'
import { Route as AppDiscountsCampaignsRouteImport } from './routes/_app.discounts.campaigns'
import { Route as AppBillingTaxInvoicesRouteImport } from './routes/_app.billing.tax-invoices'
import { Route as AppBillingTallySyncRouteImport } from './routes/_app.billing.tally-sync'
import { Route as AppBillingSalesBillsRouteImport } from './routes/_app.billing.sales-bills'
import { Route as AppBillingReportsRouteImport } from './routes/_app.billing.reports'
import { Route as AppBillingRefundsRouteImport } from './routes/_app.billing.refunds'
import { Route as AppBillingPaymentsRouteImport } from './routes/_app.billing.payments'
import { Route as AppBillingGatewayRouteImport } from './routes/_app.billing.gateway'
import { Route as AppBillingCreateInvoiceRouteImport } from './routes/_app.billing.create-invoice'
import { Route as AppAttendanceSettingsRouteImport } from './routes/_app.attendance.settings'
import { Route as AppAttendanceReportsRouteImport } from './routes/_app.attendance.reports'
import { Route as AppAttendanceLogsRouteImport } from './routes/_app.attendance.logs'
import { Route as AppAttendanceLiveRouteImport } from './routes/_app.attendance.live'
import { Route as AppAttendanceLateRouteImport } from './routes/_app.attendance.late'
import { Route as AppAttendanceHistoryRouteImport } from './routes/_app.attendance.history'
import { Route as AppAttendanceAbsentRouteImport } from './routes/_app.attendance.absent'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscountsRoute = AppDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppPosIndexRoute = AppPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPosRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppDiscountsIndexRoute = AppDiscountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppSettingsTallyRoute = AppSettingsTallyRouteImport.update({
  id: '/settings/tally',
  path: '/settings/tally',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentGatewayRoute =
  AppSettingsPaymentGatewayRouteImport.update({
    id: '/settings/payment-gateway',
    path: '/settings/payment-gateway',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAttendanceRoute = AppSettingsAttendanceRouteImport.update({
  id: '/settings/attendance',
  path: '/settings/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInventoryRoute = AppReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsFinancialRoute = AppReportsFinancialRouteImport.update({
  id: '/reports/financial',
  path: '/reports/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsExportRoute = AppReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsEmployeeRoute = AppReportsEmployeeRouteImport.update({
  id: '/reports/employee',
  path: '/reports/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsDiscountRoute = AppReportsDiscountRouteImport.update({
  id: '/reports/discount',
  path: '/reports/discount',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAttendanceRoute = AppReportsAttendanceRouteImport.update({
  id: '/reports/attendance',
  path: '/reports/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppPosTransactionsRoute = AppPosTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosSettingsRoute = AppPosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosSearchRoute = AppPosSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosQrRoute = AppPosQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosBarcodeRoute = AppPosBarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => AppPosRoute,
} as any)
const AppNotificationsSystemRoute = AppNotificationsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppNotificationsPaymentRoute = AppNotificationsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppNotificationsLowStockRoute =
  AppNotificationsLowStockRouteImport.update({
    id: '/low-stock',
    path: '/low-stock',
    getParentRoute: () => AppNotificationsRoute,
  } as any)
const AppNotificationsAttendanceRoute =
  AppNotificationsAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AppNotificationsRoute,
  } as any)
const AppInventoryStockOutwardRoute =
  AppInventoryStockOutwardRouteImport.update({
    id: '/stock-outward',
    path: '/stock-outward',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryStockInwardRoute = AppInventoryStockInwardRouteImport.update({
  id: '/stock-inward',
  path: '/stock-inward',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockAdjustmentRoute =
  AppInventoryStockAdjustmentRouteImport.update({
    id: '/stock-adjustment',
    path: '/stock-adjustment',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryReportsRoute = AppInventoryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryHistoryRoute = AppInventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryAlertsRoute = AppInventoryAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppEmployeesReportsRoute = AppEmployeesReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesProfileRoute = AppEmployeesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesLoginMonitoringRoute =
  AppEmployeesLoginMonitoringRouteImport.update({
    id: '/login-monitoring',
    path: '/login-monitoring',
    getParentRoute: () => AppEmployeesRoute,
  } as any)
const AppEmployeesLocationRoute = AppEmployeesLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesAddRoute = AppEmployeesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesActivityRoute = AppEmployeesActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppDiscountsUsageReportsRoute =
  AppDiscountsUsageReportsRouteImport.update({
    id: '/usage-reports',
    path: '/usage-reports',
    getParentRoute: () => AppDiscountsRoute,
  } as any)
const AppDiscountsSeasonalRoute = AppDiscountsSeasonalRouteImport.update({
  id: '/seasonal',
  path: '/seasonal',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppDiscountsProductsRoute = AppDiscountsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppDiscountsPercentageRoute = AppDiscountsPercentageRouteImport.update({
  id: '/percentage',
  path: '/percentage',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppDiscountsFlatRoute = AppDiscountsFlatRouteImport.update({
  id: '/flat',
  path: '/flat',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppDiscountsCategoriesRoute = AppDiscountsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppDiscountsCampaignsRoute = AppDiscountsCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppBillingTaxInvoicesRoute = AppBillingTaxInvoicesRouteImport.update({
  id: '/tax-invoices',
  path: '/tax-invoices',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingTallySyncRoute = AppBillingTallySyncRouteImport.update({
  id: '/tally-sync',
  path: '/tally-sync',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingSalesBillsRoute = AppBillingSalesBillsRouteImport.update({
  id: '/sales-bills',
  path: '/sales-bills',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingReportsRoute = AppBillingReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingRefundsRoute = AppBillingRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingPaymentsRoute = AppBillingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingGatewayRoute = AppBillingGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingCreateInvoiceRoute = AppBillingCreateInvoiceRouteImport.update({
  id: '/create-invoice',
  path: '/create-invoice',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppAttendanceSettingsRoute = AppAttendanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceReportsRoute = AppAttendanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceLogsRoute = AppAttendanceLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceLiveRoute = AppAttendanceLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceLateRoute = AppAttendanceLateRouteImport.update({
  id: '/late',
  path: '/late',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceHistoryRoute = AppAttendanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceAbsentRoute = AppAttendanceAbsentRouteImport.update({
  id: '/absent',
  path: '/absent',
  getParentRoute: () => AppAttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRouteWithChildren
  '/billing': typeof AppBillingRouteWithChildren
  '/discounts': typeof AppDiscountsRouteWithChildren
  '/employees': typeof AppEmployeesRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/notifications': typeof AppNotificationsRouteWithChildren
  '/pos': typeof AppPosRouteWithChildren
  '/attendance/absent': typeof AppAttendanceAbsentRoute
  '/attendance/history': typeof AppAttendanceHistoryRoute
  '/attendance/late': typeof AppAttendanceLateRoute
  '/attendance/live': typeof AppAttendanceLiveRoute
  '/attendance/logs': typeof AppAttendanceLogsRoute
  '/attendance/reports': typeof AppAttendanceReportsRoute
  '/attendance/settings': typeof AppAttendanceSettingsRoute
  '/billing/create-invoice': typeof AppBillingCreateInvoiceRoute
  '/billing/gateway': typeof AppBillingGatewayRoute
  '/billing/payments': typeof AppBillingPaymentsRoute
  '/billing/refunds': typeof AppBillingRefundsRoute
  '/billing/reports': typeof AppBillingReportsRoute
  '/billing/sales-bills': typeof AppBillingSalesBillsRoute
  '/billing/tally-sync': typeof AppBillingTallySyncRoute
  '/billing/tax-invoices': typeof AppBillingTaxInvoicesRoute
  '/discounts/campaigns': typeof AppDiscountsCampaignsRoute
  '/discounts/categories': typeof AppDiscountsCategoriesRoute
  '/discounts/flat': typeof AppDiscountsFlatRoute
  '/discounts/percentage': typeof AppDiscountsPercentageRoute
  '/discounts/products': typeof AppDiscountsProductsRoute
  '/discounts/seasonal': typeof AppDiscountsSeasonalRoute
  '/discounts/usage-reports': typeof AppDiscountsUsageReportsRoute
  '/employees/activity': typeof AppEmployeesActivityRoute
  '/employees/add': typeof AppEmployeesAddRoute
  '/employees/location': typeof AppEmployeesLocationRoute
  '/employees/login-monitoring': typeof AppEmployeesLoginMonitoringRoute
  '/employees/profile': typeof AppEmployeesProfileRoute
  '/employees/reports': typeof AppEmployeesReportsRoute
  '/inventory/alerts': typeof AppInventoryAlertsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/history': typeof AppInventoryHistoryRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/stock-adjustment': typeof AppInventoryStockAdjustmentRoute
  '/inventory/stock-inward': typeof AppInventoryStockInwardRoute
  '/inventory/stock-outward': typeof AppInventoryStockOutwardRoute
  '/notifications/attendance': typeof AppNotificationsAttendanceRoute
  '/notifications/low-stock': typeof AppNotificationsLowStockRoute
  '/notifications/payment': typeof AppNotificationsPaymentRoute
  '/notifications/system': typeof AppNotificationsSystemRoute
  '/pos/barcode': typeof AppPosBarcodeRoute
  '/pos/qr': typeof AppPosQrRoute
  '/pos/search': typeof AppPosSearchRoute
  '/pos/settings': typeof AppPosSettingsRoute
  '/pos/transactions': typeof AppPosTransactionsRoute
  '/reports/attendance': typeof AppReportsAttendanceRoute
  '/reports/discount': typeof AppReportsDiscountRoute
  '/reports/employee': typeof AppReportsEmployeeRoute
  '/reports/export': typeof AppReportsExportRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/settings/attendance': typeof AppSettingsAttendanceRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/payment-gateway': typeof AppSettingsPaymentGatewayRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/tally': typeof AppSettingsTallyRoute
  '/billing/': typeof AppBillingIndexRoute
  '/discounts/': typeof AppDiscountsIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/pos/': typeof AppPosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRouteWithChildren
  '/employees': typeof AppEmployeesRouteWithChildren
  '/': typeof AppIndexRoute
  '/attendance/absent': typeof AppAttendanceAbsentRoute
  '/attendance/history': typeof AppAttendanceHistoryRoute
  '/attendance/late': typeof AppAttendanceLateRoute
  '/attendance/live': typeof AppAttendanceLiveRoute
  '/attendance/logs': typeof AppAttendanceLogsRoute
  '/attendance/reports': typeof AppAttendanceReportsRoute
  '/attendance/settings': typeof AppAttendanceSettingsRoute
  '/billing/create-invoice': typeof AppBillingCreateInvoiceRoute
  '/billing/gateway': typeof AppBillingGatewayRoute
  '/billing/payments': typeof AppBillingPaymentsRoute
  '/billing/refunds': typeof AppBillingRefundsRoute
  '/billing/reports': typeof AppBillingReportsRoute
  '/billing/sales-bills': typeof AppBillingSalesBillsRoute
  '/billing/tally-sync': typeof AppBillingTallySyncRoute
  '/billing/tax-invoices': typeof AppBillingTaxInvoicesRoute
  '/discounts/campaigns': typeof AppDiscountsCampaignsRoute
  '/discounts/categories': typeof AppDiscountsCategoriesRoute
  '/discounts/flat': typeof AppDiscountsFlatRoute
  '/discounts/percentage': typeof AppDiscountsPercentageRoute
  '/discounts/products': typeof AppDiscountsProductsRoute
  '/discounts/seasonal': typeof AppDiscountsSeasonalRoute
  '/discounts/usage-reports': typeof AppDiscountsUsageReportsRoute
  '/employees/activity': typeof AppEmployeesActivityRoute
  '/employees/add': typeof AppEmployeesAddRoute
  '/employees/location': typeof AppEmployeesLocationRoute
  '/employees/login-monitoring': typeof AppEmployeesLoginMonitoringRoute
  '/employees/profile': typeof AppEmployeesProfileRoute
  '/employees/reports': typeof AppEmployeesReportsRoute
  '/inventory/alerts': typeof AppInventoryAlertsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/history': typeof AppInventoryHistoryRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/stock-adjustment': typeof AppInventoryStockAdjustmentRoute
  '/inventory/stock-inward': typeof AppInventoryStockInwardRoute
  '/inventory/stock-outward': typeof AppInventoryStockOutwardRoute
  '/notifications/attendance': typeof AppNotificationsAttendanceRoute
  '/notifications/low-stock': typeof AppNotificationsLowStockRoute
  '/notifications/payment': typeof AppNotificationsPaymentRoute
  '/notifications/system': typeof AppNotificationsSystemRoute
  '/pos/barcode': typeof AppPosBarcodeRoute
  '/pos/qr': typeof AppPosQrRoute
  '/pos/search': typeof AppPosSearchRoute
  '/pos/settings': typeof AppPosSettingsRoute
  '/pos/transactions': typeof AppPosTransactionsRoute
  '/reports/attendance': typeof AppReportsAttendanceRoute
  '/reports/discount': typeof AppReportsDiscountRoute
  '/reports/employee': typeof AppReportsEmployeeRoute
  '/reports/export': typeof AppReportsExportRoute
  '/reports/financial': typeof AppReportsFinancialRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/settings/attendance': typeof AppSettingsAttendanceRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/payment-gateway': typeof AppSettingsPaymentGatewayRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/tally': typeof AppSettingsTallyRoute
  '/billing': typeof AppBillingIndexRoute
  '/discounts': typeof AppDiscountsIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/pos': typeof AppPosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRouteWithChildren
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/discounts': typeof AppDiscountsRouteWithChildren
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRouteWithChildren
  '/_app/pos': typeof AppPosRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/attendance/absent': typeof AppAttendanceAbsentRoute
  '/_app/attendance/history': typeof AppAttendanceHistoryRoute
  '/_app/attendance/late': typeof AppAttendanceLateRoute
  '/_app/attendance/live': typeof AppAttendanceLiveRoute
  '/_app/attendance/logs': typeof AppAttendanceLogsRoute
  '/_app/attendance/reports': typeof AppAttendanceReportsRoute
  '/_app/attendance/settings': typeof AppAttendanceSettingsRoute
  '/_app/billing/create-invoice': typeof AppBillingCreateInvoiceRoute
  '/_app/billing/gateway': typeof AppBillingGatewayRoute
  '/_app/billing/payments': typeof AppBillingPaymentsRoute
  '/_app/billing/refunds': typeof AppBillingRefundsRoute
  '/_app/billing/reports': typeof AppBillingReportsRoute
  '/_app/billing/sales-bills': typeof AppBillingSalesBillsRoute
  '/_app/billing/tally-sync': typeof AppBillingTallySyncRoute
  '/_app/billing/tax-invoices': typeof AppBillingTaxInvoicesRoute
  '/_app/discounts/campaigns': typeof AppDiscountsCampaignsRoute
  '/_app/discounts/categories': typeof AppDiscountsCategoriesRoute
  '/_app/discounts/flat': typeof AppDiscountsFlatRoute
  '/_app/discounts/percentage': typeof AppDiscountsPercentageRoute
  '/_app/discounts/products': typeof AppDiscountsProductsRoute
  '/_app/discounts/seasonal': typeof AppDiscountsSeasonalRoute
  '/_app/discounts/usage-reports': typeof AppDiscountsUsageReportsRoute
  '/_app/employees/activity': typeof AppEmployeesActivityRoute
  '/_app/employees/add': typeof AppEmployeesAddRoute
  '/_app/employees/location': typeof AppEmployeesLocationRoute
  '/_app/employees/login-monitoring': typeof AppEmployeesLoginMonitoringRoute
  '/_app/employees/profile': typeof AppEmployeesProfileRoute
  '/_app/employees/reports': typeof AppEmployeesReportsRoute
  '/_app/inventory/alerts': typeof AppInventoryAlertsRoute
  '/_app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/_app/inventory/history': typeof AppInventoryHistoryRoute
  '/_app/inventory/products': typeof AppInventoryProductsRoute
  '/_app/inventory/reports': typeof AppInventoryReportsRoute
  '/_app/inventory/stock-adjustment': typeof AppInventoryStockAdjustmentRoute
  '/_app/inventory/stock-inward': typeof AppInventoryStockInwardRoute
  '/_app/inventory/stock-outward': typeof AppInventoryStockOutwardRoute
  '/_app/notifications/attendance': typeof AppNotificationsAttendanceRoute
  '/_app/notifications/low-stock': typeof AppNotificationsLowStockRoute
  '/_app/notifications/payment': typeof AppNotificationsPaymentRoute
  '/_app/notifications/system': typeof AppNotificationsSystemRoute
  '/_app/pos/barcode': typeof AppPosBarcodeRoute
  '/_app/pos/qr': typeof AppPosQrRoute
  '/_app/pos/search': typeof AppPosSearchRoute
  '/_app/pos/settings': typeof AppPosSettingsRoute
  '/_app/pos/transactions': typeof AppPosTransactionsRoute
  '/_app/reports/attendance': typeof AppReportsAttendanceRoute
  '/_app/reports/discount': typeof AppReportsDiscountRoute
  '/_app/reports/employee': typeof AppReportsEmployeeRoute
  '/_app/reports/export': typeof AppReportsExportRoute
  '/_app/reports/financial': typeof AppReportsFinancialRoute
  '/_app/reports/inventory': typeof AppReportsInventoryRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/settings/attendance': typeof AppSettingsAttendanceRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/payment-gateway': typeof AppSettingsPaymentGatewayRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/tally': typeof AppSettingsTallyRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/discounts/': typeof AppDiscountsIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/pos/': typeof AppPosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/billing'
    | '/discounts'
    | '/employees'
    | '/inventory'
    | '/notifications'
    | '/pos'
    | '/attendance/absent'
    | '/attendance/history'
    | '/attendance/late'
    | '/attendance/live'
    | '/attendance/logs'
    | '/attendance/reports'
    | '/attendance/settings'
    | '/billing/create-invoice'
    | '/billing/gateway'
    | '/billing/payments'
    | '/billing/refunds'
    | '/billing/reports'
    | '/billing/sales-bills'
    | '/billing/tally-sync'
    | '/billing/tax-invoices'
    | '/discounts/campaigns'
    | '/discounts/categories'
    | '/discounts/flat'
    | '/discounts/percentage'
    | '/discounts/products'
    | '/discounts/seasonal'
    | '/discounts/usage-reports'
    | '/employees/activity'
    | '/employees/add'
    | '/employees/location'
    | '/employees/login-monitoring'
    | '/employees/profile'
    | '/employees/reports'
    | '/inventory/alerts'
    | '/inventory/categories'
    | '/inventory/history'
    | '/inventory/products'
    | '/inventory/reports'
    | '/inventory/stock-adjustment'
    | '/inventory/stock-inward'
    | '/inventory/stock-outward'
    | '/notifications/attendance'
    | '/notifications/low-stock'
    | '/notifications/payment'
    | '/notifications/system'
    | '/pos/barcode'
    | '/pos/qr'
    | '/pos/search'
    | '/pos/settings'
    | '/pos/transactions'
    | '/reports/attendance'
    | '/reports/discount'
    | '/reports/employee'
    | '/reports/export'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/attendance'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/payment-gateway'
    | '/settings/preferences'
    | '/settings/roles'
    | '/settings/tally'
    | '/billing/'
    | '/discounts/'
    | '/inventory/'
    | '/notifications/'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/employees'
    | '/'
    | '/attendance/absent'
    | '/attendance/history'
    | '/attendance/late'
    | '/attendance/live'
    | '/attendance/logs'
    | '/attendance/reports'
    | '/attendance/settings'
    | '/billing/create-invoice'
    | '/billing/gateway'
    | '/billing/payments'
    | '/billing/refunds'
    | '/billing/reports'
    | '/billing/sales-bills'
    | '/billing/tally-sync'
    | '/billing/tax-invoices'
    | '/discounts/campaigns'
    | '/discounts/categories'
    | '/discounts/flat'
    | '/discounts/percentage'
    | '/discounts/products'
    | '/discounts/seasonal'
    | '/discounts/usage-reports'
    | '/employees/activity'
    | '/employees/add'
    | '/employees/location'
    | '/employees/login-monitoring'
    | '/employees/profile'
    | '/employees/reports'
    | '/inventory/alerts'
    | '/inventory/categories'
    | '/inventory/history'
    | '/inventory/products'
    | '/inventory/reports'
    | '/inventory/stock-adjustment'
    | '/inventory/stock-inward'
    | '/inventory/stock-outward'
    | '/notifications/attendance'
    | '/notifications/low-stock'
    | '/notifications/payment'
    | '/notifications/system'
    | '/pos/barcode'
    | '/pos/qr'
    | '/pos/search'
    | '/pos/settings'
    | '/pos/transactions'
    | '/reports/attendance'
    | '/reports/discount'
    | '/reports/employee'
    | '/reports/export'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/attendance'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/payment-gateway'
    | '/settings/preferences'
    | '/settings/roles'
    | '/settings/tally'
    | '/billing'
    | '/discounts'
    | '/inventory'
    | '/notifications'
    | '/pos'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/billing'
    | '/_app/discounts'
    | '/_app/employees'
    | '/_app/inventory'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/'
    | '/_app/attendance/absent'
    | '/_app/attendance/history'
    | '/_app/attendance/late'
    | '/_app/attendance/live'
    | '/_app/attendance/logs'
    | '/_app/attendance/reports'
    | '/_app/attendance/settings'
    | '/_app/billing/create-invoice'
    | '/_app/billing/gateway'
    | '/_app/billing/payments'
    | '/_app/billing/refunds'
    | '/_app/billing/reports'
    | '/_app/billing/sales-bills'
    | '/_app/billing/tally-sync'
    | '/_app/billing/tax-invoices'
    | '/_app/discounts/campaigns'
    | '/_app/discounts/categories'
    | '/_app/discounts/flat'
    | '/_app/discounts/percentage'
    | '/_app/discounts/products'
    | '/_app/discounts/seasonal'
    | '/_app/discounts/usage-reports'
    | '/_app/employees/activity'
    | '/_app/employees/add'
    | '/_app/employees/location'
    | '/_app/employees/login-monitoring'
    | '/_app/employees/profile'
    | '/_app/employees/reports'
    | '/_app/inventory/alerts'
    | '/_app/inventory/categories'
    | '/_app/inventory/history'
    | '/_app/inventory/products'
    | '/_app/inventory/reports'
    | '/_app/inventory/stock-adjustment'
    | '/_app/inventory/stock-inward'
    | '/_app/inventory/stock-outward'
    | '/_app/notifications/attendance'
    | '/_app/notifications/low-stock'
    | '/_app/notifications/payment'
    | '/_app/notifications/system'
    | '/_app/pos/barcode'
    | '/_app/pos/qr'
    | '/_app/pos/search'
    | '/_app/pos/settings'
    | '/_app/pos/transactions'
    | '/_app/reports/attendance'
    | '/_app/reports/discount'
    | '/_app/reports/employee'
    | '/_app/reports/export'
    | '/_app/reports/financial'
    | '/_app/reports/inventory'
    | '/_app/reports/sales'
    | '/_app/settings/attendance'
    | '/_app/settings/company'
    | '/_app/settings/notifications'
    | '/_app/settings/payment-gateway'
    | '/_app/settings/preferences'
    | '/_app/settings/roles'
    | '/_app/settings/tally'
    | '/_app/billing/'
    | '/_app/discounts/'
    | '/_app/inventory/'
    | '/_app/notifications/'
    | '/_app/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discounts': {
      id: '/_app/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/': {
      id: '/_app/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof AppPosIndexRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/discounts/': {
      id: '/_app/discounts/'
      path: '/'
      fullPath: '/discounts/'
      preLoaderRoute: typeof AppDiscountsIndexRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/settings/tally': {
      id: '/_app/settings/tally'
      path: '/settings/tally'
      fullPath: '/settings/tally'
      preLoaderRoute: typeof AppSettingsTallyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/payment-gateway': {
      id: '/_app/settings/payment-gateway'
      path: '/settings/payment-gateway'
      fullPath: '/settings/payment-gateway'
      preLoaderRoute: typeof AppSettingsPaymentGatewayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/attendance': {
      id: '/_app/settings/attendance'
      path: '/settings/attendance'
      fullPath: '/settings/attendance'
      preLoaderRoute: typeof AppSettingsAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory': {
      id: '/_app/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AppReportsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/financial': {
      id: '/_app/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AppReportsFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/export': {
      id: '/_app/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AppReportsExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/employee': {
      id: '/_app/reports/employee'
      path: '/reports/employee'
      fullPath: '/reports/employee'
      preLoaderRoute: typeof AppReportsEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/discount': {
      id: '/_app/reports/discount'
      path: '/reports/discount'
      fullPath: '/reports/discount'
      preLoaderRoute: typeof AppReportsDiscountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/attendance': {
      id: '/_app/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AppReportsAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/transactions': {
      id: '/_app/pos/transactions'
      path: '/transactions'
      fullPath: '/pos/transactions'
      preLoaderRoute: typeof AppPosTransactionsRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/settings': {
      id: '/_app/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof AppPosSettingsRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/search': {
      id: '/_app/pos/search'
      path: '/search'
      fullPath: '/pos/search'
      preLoaderRoute: typeof AppPosSearchRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/qr': {
      id: '/_app/pos/qr'
      path: '/qr'
      fullPath: '/pos/qr'
      preLoaderRoute: typeof AppPosQrRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/barcode': {
      id: '/_app/pos/barcode'
      path: '/barcode'
      fullPath: '/pos/barcode'
      preLoaderRoute: typeof AppPosBarcodeRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/notifications/system': {
      id: '/_app/notifications/system'
      path: '/system'
      fullPath: '/notifications/system'
      preLoaderRoute: typeof AppNotificationsSystemRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/notifications/payment': {
      id: '/_app/notifications/payment'
      path: '/payment'
      fullPath: '/notifications/payment'
      preLoaderRoute: typeof AppNotificationsPaymentRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/notifications/low-stock': {
      id: '/_app/notifications/low-stock'
      path: '/low-stock'
      fullPath: '/notifications/low-stock'
      preLoaderRoute: typeof AppNotificationsLowStockRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/notifications/attendance': {
      id: '/_app/notifications/attendance'
      path: '/attendance'
      fullPath: '/notifications/attendance'
      preLoaderRoute: typeof AppNotificationsAttendanceRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/inventory/stock-outward': {
      id: '/_app/inventory/stock-outward'
      path: '/stock-outward'
      fullPath: '/inventory/stock-outward'
      preLoaderRoute: typeof AppInventoryStockOutwardRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-inward': {
      id: '/_app/inventory/stock-inward'
      path: '/stock-inward'
      fullPath: '/inventory/stock-inward'
      preLoaderRoute: typeof AppInventoryStockInwardRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-adjustment': {
      id: '/_app/inventory/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/inventory/stock-adjustment'
      preLoaderRoute: typeof AppInventoryStockAdjustmentRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/reports': {
      id: '/_app/inventory/reports'
      path: '/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof AppInventoryReportsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/history': {
      id: '/_app/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof AppInventoryHistoryRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/categories': {
      id: '/_app/inventory/categories'
      path: '/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/alerts': {
      id: '/_app/inventory/alerts'
      path: '/alerts'
      fullPath: '/inventory/alerts'
      preLoaderRoute: typeof AppInventoryAlertsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/employees/reports': {
      id: '/_app/employees/reports'
      path: '/reports'
      fullPath: '/employees/reports'
      preLoaderRoute: typeof AppEmployeesReportsRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/profile': {
      id: '/_app/employees/profile'
      path: '/profile'
      fullPath: '/employees/profile'
      preLoaderRoute: typeof AppEmployeesProfileRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/login-monitoring': {
      id: '/_app/employees/login-monitoring'
      path: '/login-monitoring'
      fullPath: '/employees/login-monitoring'
      preLoaderRoute: typeof AppEmployeesLoginMonitoringRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/location': {
      id: '/_app/employees/location'
      path: '/location'
      fullPath: '/employees/location'
      preLoaderRoute: typeof AppEmployeesLocationRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/add': {
      id: '/_app/employees/add'
      path: '/add'
      fullPath: '/employees/add'
      preLoaderRoute: typeof AppEmployeesAddRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/activity': {
      id: '/_app/employees/activity'
      path: '/activity'
      fullPath: '/employees/activity'
      preLoaderRoute: typeof AppEmployeesActivityRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/discounts/usage-reports': {
      id: '/_app/discounts/usage-reports'
      path: '/usage-reports'
      fullPath: '/discounts/usage-reports'
      preLoaderRoute: typeof AppDiscountsUsageReportsRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/seasonal': {
      id: '/_app/discounts/seasonal'
      path: '/seasonal'
      fullPath: '/discounts/seasonal'
      preLoaderRoute: typeof AppDiscountsSeasonalRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/products': {
      id: '/_app/discounts/products'
      path: '/products'
      fullPath: '/discounts/products'
      preLoaderRoute: typeof AppDiscountsProductsRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/percentage': {
      id: '/_app/discounts/percentage'
      path: '/percentage'
      fullPath: '/discounts/percentage'
      preLoaderRoute: typeof AppDiscountsPercentageRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/flat': {
      id: '/_app/discounts/flat'
      path: '/flat'
      fullPath: '/discounts/flat'
      preLoaderRoute: typeof AppDiscountsFlatRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/categories': {
      id: '/_app/discounts/categories'
      path: '/categories'
      fullPath: '/discounts/categories'
      preLoaderRoute: typeof AppDiscountsCategoriesRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/discounts/campaigns': {
      id: '/_app/discounts/campaigns'
      path: '/campaigns'
      fullPath: '/discounts/campaigns'
      preLoaderRoute: typeof AppDiscountsCampaignsRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/billing/tax-invoices': {
      id: '/_app/billing/tax-invoices'
      path: '/tax-invoices'
      fullPath: '/billing/tax-invoices'
      preLoaderRoute: typeof AppBillingTaxInvoicesRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/tally-sync': {
      id: '/_app/billing/tally-sync'
      path: '/tally-sync'
      fullPath: '/billing/tally-sync'
      preLoaderRoute: typeof AppBillingTallySyncRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/sales-bills': {
      id: '/_app/billing/sales-bills'
      path: '/sales-bills'
      fullPath: '/billing/sales-bills'
      preLoaderRoute: typeof AppBillingSalesBillsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/reports': {
      id: '/_app/billing/reports'
      path: '/reports'
      fullPath: '/billing/reports'
      preLoaderRoute: typeof AppBillingReportsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/refunds': {
      id: '/_app/billing/refunds'
      path: '/refunds'
      fullPath: '/billing/refunds'
      preLoaderRoute: typeof AppBillingRefundsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/payments': {
      id: '/_app/billing/payments'
      path: '/payments'
      fullPath: '/billing/payments'
      preLoaderRoute: typeof AppBillingPaymentsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/gateway': {
      id: '/_app/billing/gateway'
      path: '/gateway'
      fullPath: '/billing/gateway'
      preLoaderRoute: typeof AppBillingGatewayRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/create-invoice': {
      id: '/_app/billing/create-invoice'
      path: '/create-invoice'
      fullPath: '/billing/create-invoice'
      preLoaderRoute: typeof AppBillingCreateInvoiceRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/attendance/settings': {
      id: '/_app/attendance/settings'
      path: '/settings'
      fullPath: '/attendance/settings'
      preLoaderRoute: typeof AppAttendanceSettingsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/reports': {
      id: '/_app/attendance/reports'
      path: '/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof AppAttendanceReportsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/logs': {
      id: '/_app/attendance/logs'
      path: '/logs'
      fullPath: '/attendance/logs'
      preLoaderRoute: typeof AppAttendanceLogsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/live': {
      id: '/_app/attendance/live'
      path: '/live'
      fullPath: '/attendance/live'
      preLoaderRoute: typeof AppAttendanceLiveRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/late': {
      id: '/_app/attendance/late'
      path: '/late'
      fullPath: '/attendance/late'
      preLoaderRoute: typeof AppAttendanceLateRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/history': {
      id: '/_app/attendance/history'
      path: '/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof AppAttendanceHistoryRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/absent': {
      id: '/_app/attendance/absent'
      path: '/absent'
      fullPath: '/attendance/absent'
      preLoaderRoute: typeof AppAttendanceAbsentRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
  }
}

interface AppAttendanceRouteChildren {
  AppAttendanceAbsentRoute: typeof AppAttendanceAbsentRoute
  AppAttendanceHistoryRoute: typeof AppAttendanceHistoryRoute
  AppAttendanceLateRoute: typeof AppAttendanceLateRoute
  AppAttendanceLiveRoute: typeof AppAttendanceLiveRoute
  AppAttendanceLogsRoute: typeof AppAttendanceLogsRoute
  AppAttendanceReportsRoute: typeof AppAttendanceReportsRoute
  AppAttendanceSettingsRoute: typeof AppAttendanceSettingsRoute
}

const AppAttendanceRouteChildren: AppAttendanceRouteChildren = {
  AppAttendanceAbsentRoute: AppAttendanceAbsentRoute,
  AppAttendanceHistoryRoute: AppAttendanceHistoryRoute,
  AppAttendanceLateRoute: AppAttendanceLateRoute,
  AppAttendanceLiveRoute: AppAttendanceLiveRoute,
  AppAttendanceLogsRoute: AppAttendanceLogsRoute,
  AppAttendanceReportsRoute: AppAttendanceReportsRoute,
  AppAttendanceSettingsRoute: AppAttendanceSettingsRoute,
}

const AppAttendanceRouteWithChildren = AppAttendanceRoute._addFileChildren(
  AppAttendanceRouteChildren,
)

interface AppBillingRouteChildren {
  AppBillingCreateInvoiceRoute: typeof AppBillingCreateInvoiceRoute
  AppBillingGatewayRoute: typeof AppBillingGatewayRoute
  AppBillingPaymentsRoute: typeof AppBillingPaymentsRoute
  AppBillingRefundsRoute: typeof AppBillingRefundsRoute
  AppBillingReportsRoute: typeof AppBillingReportsRoute
  AppBillingSalesBillsRoute: typeof AppBillingSalesBillsRoute
  AppBillingTallySyncRoute: typeof AppBillingTallySyncRoute
  AppBillingTaxInvoicesRoute: typeof AppBillingTaxInvoicesRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingCreateInvoiceRoute: AppBillingCreateInvoiceRoute,
  AppBillingGatewayRoute: AppBillingGatewayRoute,
  AppBillingPaymentsRoute: AppBillingPaymentsRoute,
  AppBillingRefundsRoute: AppBillingRefundsRoute,
  AppBillingReportsRoute: AppBillingReportsRoute,
  AppBillingSalesBillsRoute: AppBillingSalesBillsRoute,
  AppBillingTallySyncRoute: AppBillingTallySyncRoute,
  AppBillingTaxInvoicesRoute: AppBillingTaxInvoicesRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppDiscountsRouteChildren {
  AppDiscountsCampaignsRoute: typeof AppDiscountsCampaignsRoute
  AppDiscountsCategoriesRoute: typeof AppDiscountsCategoriesRoute
  AppDiscountsFlatRoute: typeof AppDiscountsFlatRoute
  AppDiscountsPercentageRoute: typeof AppDiscountsPercentageRoute
  AppDiscountsProductsRoute: typeof AppDiscountsProductsRoute
  AppDiscountsSeasonalRoute: typeof AppDiscountsSeasonalRoute
  AppDiscountsUsageReportsRoute: typeof AppDiscountsUsageReportsRoute
  AppDiscountsIndexRoute: typeof AppDiscountsIndexRoute
}

const AppDiscountsRouteChildren: AppDiscountsRouteChildren = {
  AppDiscountsCampaignsRoute: AppDiscountsCampaignsRoute,
  AppDiscountsCategoriesRoute: AppDiscountsCategoriesRoute,
  AppDiscountsFlatRoute: AppDiscountsFlatRoute,
  AppDiscountsPercentageRoute: AppDiscountsPercentageRoute,
  AppDiscountsProductsRoute: AppDiscountsProductsRoute,
  AppDiscountsSeasonalRoute: AppDiscountsSeasonalRoute,
  AppDiscountsUsageReportsRoute: AppDiscountsUsageReportsRoute,
  AppDiscountsIndexRoute: AppDiscountsIndexRoute,
}

const AppDiscountsRouteWithChildren = AppDiscountsRoute._addFileChildren(
  AppDiscountsRouteChildren,
)

interface AppEmployeesRouteChildren {
  AppEmployeesActivityRoute: typeof AppEmployeesActivityRoute
  AppEmployeesAddRoute: typeof AppEmployeesAddRoute
  AppEmployeesLocationRoute: typeof AppEmployeesLocationRoute
  AppEmployeesLoginMonitoringRoute: typeof AppEmployeesLoginMonitoringRoute
  AppEmployeesProfileRoute: typeof AppEmployeesProfileRoute
  AppEmployeesReportsRoute: typeof AppEmployeesReportsRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesActivityRoute: AppEmployeesActivityRoute,
  AppEmployeesAddRoute: AppEmployeesAddRoute,
  AppEmployeesLocationRoute: AppEmployeesLocationRoute,
  AppEmployeesLoginMonitoringRoute: AppEmployeesLoginMonitoringRoute,
  AppEmployeesProfileRoute: AppEmployeesProfileRoute,
  AppEmployeesReportsRoute: AppEmployeesReportsRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryAlertsRoute: typeof AppInventoryAlertsRoute
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryHistoryRoute: typeof AppInventoryHistoryRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryReportsRoute: typeof AppInventoryReportsRoute
  AppInventoryStockAdjustmentRoute: typeof AppInventoryStockAdjustmentRoute
  AppInventoryStockInwardRoute: typeof AppInventoryStockInwardRoute
  AppInventoryStockOutwardRoute: typeof AppInventoryStockOutwardRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryAlertsRoute: AppInventoryAlertsRoute,
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryHistoryRoute: AppInventoryHistoryRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryReportsRoute: AppInventoryReportsRoute,
  AppInventoryStockAdjustmentRoute: AppInventoryStockAdjustmentRoute,
  AppInventoryStockInwardRoute: AppInventoryStockInwardRoute,
  AppInventoryStockOutwardRoute: AppInventoryStockOutwardRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppNotificationsRouteChildren {
  AppNotificationsAttendanceRoute: typeof AppNotificationsAttendanceRoute
  AppNotificationsLowStockRoute: typeof AppNotificationsLowStockRoute
  AppNotificationsPaymentRoute: typeof AppNotificationsPaymentRoute
  AppNotificationsSystemRoute: typeof AppNotificationsSystemRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
}

const AppNotificationsRouteChildren: AppNotificationsRouteChildren = {
  AppNotificationsAttendanceRoute: AppNotificationsAttendanceRoute,
  AppNotificationsLowStockRoute: AppNotificationsLowStockRoute,
  AppNotificationsPaymentRoute: AppNotificationsPaymentRoute,
  AppNotificationsSystemRoute: AppNotificationsSystemRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
}

const AppNotificationsRouteWithChildren =
  AppNotificationsRoute._addFileChildren(AppNotificationsRouteChildren)

interface AppPosRouteChildren {
  AppPosBarcodeRoute: typeof AppPosBarcodeRoute
  AppPosQrRoute: typeof AppPosQrRoute
  AppPosSearchRoute: typeof AppPosSearchRoute
  AppPosSettingsRoute: typeof AppPosSettingsRoute
  AppPosTransactionsRoute: typeof AppPosTransactionsRoute
  AppPosIndexRoute: typeof AppPosIndexRoute
}

const AppPosRouteChildren: AppPosRouteChildren = {
  AppPosBarcodeRoute: AppPosBarcodeRoute,
  AppPosQrRoute: AppPosQrRoute,
  AppPosSearchRoute: AppPosSearchRoute,
  AppPosSettingsRoute: AppPosSettingsRoute,
  AppPosTransactionsRoute: AppPosTransactionsRoute,
  AppPosIndexRoute: AppPosIndexRoute,
}

const AppPosRouteWithChildren =
  AppPosRoute._addFileChildren(AppPosRouteChildren)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRouteWithChildren
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDiscountsRoute: typeof AppDiscountsRouteWithChildren
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRouteWithChildren
  AppPosRoute: typeof AppPosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppReportsAttendanceRoute: typeof AppReportsAttendanceRoute
  AppReportsDiscountRoute: typeof AppReportsDiscountRoute
  AppReportsEmployeeRoute: typeof AppReportsEmployeeRoute
  AppReportsExportRoute: typeof AppReportsExportRoute
  AppReportsFinancialRoute: typeof AppReportsFinancialRoute
  AppReportsInventoryRoute: typeof AppReportsInventoryRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppSettingsAttendanceRoute: typeof AppSettingsAttendanceRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPaymentGatewayRoute: typeof AppSettingsPaymentGatewayRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsTallyRoute: typeof AppSettingsTallyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRouteWithChildren,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDiscountsRoute: AppDiscountsRouteWithChildren,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRouteWithChildren,
  AppPosRoute: AppPosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppReportsAttendanceRoute: AppReportsAttendanceRoute,
  AppReportsDiscountRoute: AppReportsDiscountRoute,
  AppReportsEmployeeRoute: AppReportsEmployeeRoute,
  AppReportsExportRoute: AppReportsExportRoute,
  AppReportsFinancialRoute: AppReportsFinancialRoute,
  AppReportsInventoryRoute: AppReportsInventoryRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppSettingsAttendanceRoute: AppSettingsAttendanceRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPaymentGatewayRoute: AppSettingsPaymentGatewayRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsTallyRoute: AppSettingsTallyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
